### ISSUE TITLE
Could you add some instructions?

### ISSUE THREAD

**Issue by littleggghost** [AMABerkeley/jelly_locomotion#1]
Hi, there
I read your code and find you guys done a great job, thanks for your sharing!
But could you add some steps and instructions in README.md?
For example:

1. Does it works under Ubuntu+ROS Kinetic?
2. How to run it? Does it should run with ros `rosrun jelly_locomotion dog_demo.py`? Or directly run it `python dog_demo.py`?
3. As dog.py write, it imports scipy, so it can only run with python3.
4. How to install PyKDL and kdl_parser_py? I tried to install them with python3, but failed.

Hope for your reply and thanks in advance!

**Comment by wuphilipp** [comment]
Hello! Thank you for your interest in our project! I currently had my hands full with some work, but am planning on doing a code update for quadruped control and will add a README then. I'll keep you posted! (And sorry for the current messy state of the repo, we had to do some hacking for a final deadline).

To quickly address your points

1. This was tested with ROS Kinetic, Ubuntu 16.04
2. You can run python dog.py to see a simple walking gait in action. This package was built to the interface as a python package with the jelly core repo (https://github.com/AMABerkeley/jelly_core), which runs on actual hardware. The dog.py was meant as a script to test gaits.
3. scipy should be able to run in python2? 
4. https://pypi.org/project/PyKDL/, which I think should also work with pyKDL. I think dog.py does not actually use pyKDL, so you can delete to run the script.

As I said I plan on updating this all and will add some instructions. Sorry for the messy code and thanks again!

**Comment by littleggghost** [comment]
Really thanks for your rapid reply of your busy schedule!
Are you attending the ICRA now? I just guess.
Now I use python2.7, and meet one last problem when install `pip install quadprog --user`:
```
Collecting quadprog
  Using cached https://files.pythonhosted.org/packages/24/fb/816f87f1b9648231b51012758b1d8fa3043ee1a428e3dbb64c6e6a42b6b9/quadprog-0.1.6.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Gb2XcE/quadprog/setup.py", line 17, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Gb2XcE/quadprog/
```
You can have a look when you have the time.
Best regards!

**Comment by littleggghost** [comment]
I figure it out. 

1. Download the [source code](https://pypi.org/project/quadprog/) of quadprog.
2. `pip install Cython --user`
3. In directory of source code, run `sudo python setup.py install`
